### ISSUE TITLE
Concerned Viewer

### ISSUE THREAD

**Issue by gichomo** [dipghoshraj/virtual-pen#3]
How will the pen work without an eraser

**Comment by dipghoshraj** [comment]
@gichomo  Thank you for your question while I am expecting this question. I am working on the eraser functionality. It will be updated very soon.

**Comment by dipghoshraj** [comment]
@gichomo  updated the eraser functionality, hopefully you can check this function. Here are the using instructions

Press button "s" to stop drawing lines
press button "e" for enable eraser
press button "p" to enable pen

Please read readme.md for more informations. 

Thanks, 
Dip Ghosh

**Comment by dipghoshraj** [comment]
This feature is added on the new release.
